#!/usr/bin/env bash
# configures a new Ubuntu machine haproxy

sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.9
sudo apt-get update
sudo apt-get -y install haproxy=1.9.\*
new_string="frontend web-front
\tbind *:80
\tdefault_backend web-backend

backend web-backend
\tbalance roundrobin
\tserver web1 104.196.35.117:80 check
\tserver web2 35.185.92.133:80 check"
echo -e "$new_string" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart