#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID

echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
while ((1));
do
    echo "To infinity and beyond"
    sleep 2
done
