#!/usr/bin/env bash
# This script displays To infinity and beyond and I am invincible!!! when signal

trap 'echo I am invincible!!!' SIGTERM
while ((1));
do
    echo "To infinity and beyond"
    sleep 2
done
