#!/usr/bin/env bash
# This script display "Holberton School" and "Hi" with while

i=0
while ((i < 10));
do
    echo "Holberton School"
    if [ $i -eq 8 ];
    then
	echo "Hi"
    fi
    ((i++))
done
