#!/usr/bin/env bash
# This script display "Holberton School" and "good luck", "bad luck" with while

i=0
while ((i < 10));
do
    if [ $i -eq 3 ];
    then
	echo "bad luck"
    elif [ $i -eq 7 ];
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
