#!/usr/bin/env bash
# This script display numbers with while and case statement

i=0
while ((i < 21));
do
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
