#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
while ((hour < 13));
do
    echo "Hour: $hour"
    mins=0
    while ((mins < 60));
    do
	echo $mins
	((mins++))
    done
    ((hour++))
done
