#!/usr/bin/env bash
# fix the container - Nginx running as the nginx user
sudo chmod 666 /etc/nginx/nginx.conf
sudo sed -i "1s/^/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo pkill -o apache2
su nginx -c "service nginx restart"
