#!/usr/bin/env bash
# fix the container - Nginx running as the nginx user
sudo chmod u+rw /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data;/#user www-data;\nuser nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
su nginx -c "service nginx restart"
